/**
 * Merchant category codes
 *
 * Generated reference data for the `/tools/*` calculators. The maintenance
 * contract is in `lib/tools-data/index.ts`: every figure here was read from a
 * primary source on the date recorded beside it, and a checked date must never
 * be moved without re-reading the source.
 *
 * ONE MODULE PER TOOL, ON PURPOSE. `/tools/[tool]` is a single route serving
 * every calculator, so anything a client widget imports lands in the chunk that
 * EVERY tool page loads. Splitting these is what keeps the 290 row MCC table off
 * the Stripe fee calculator. Do not merge them back into one file, and do not
 * import from `lib/tools-data/index.ts` inside a `"use client"` module.
 */

export interface MccEntry {
  code: string;
  description: string;
  group: string;
  /**
   * Commonly treated as elevated risk by US acquirers during underwriting.
   *
   * A market observation, NOT a card network classification: no network
   * publishes a "high risk MCC" list and acquirers disagree with each other. The
   * UI labels the column accordingly.
   */
  highRisk: boolean;
}

export const MCC_GROUPS: string[] = [
  "Agriculture and Veterinary",
  "Automotive",
  "Business and Professional Services",
  "Clothing and Accessories",
  "Contractors and Trades",
  "Digital Goods and Direct Marketing",
  "Education",
  "Electronics and Computers",
  "Entertainment and Recreation",
  "Financial Services",
  "Food and Grocery",
  "General and Department Stores",
  "Government and Public Sector",
  "Health and Medical",
  "Home, Garden and Building Supply",
  "Membership and Nonprofit",
  "Personal Services",
  "Restaurants and Bars",
  "Specialty and Hobby Retail",
  "Transportation and Freight",
  "Travel and Lodging",
  "Utilities and Telecom",
  "Wholesale and Distributors",
];

export const MCC_CODES: MccEntry[] = [
  {
    code: "0742",
    description: "Veterinary Services",
    group: "Agriculture and Veterinary",
    highRisk: false,
  },
  {
    code: "0763",
    description: "Agricultural Co-operatives",
    group: "Agriculture and Veterinary",
    highRisk: false,
  },
  {
    code: "0780",
    description: "Landscaping and Horticultural Services",
    group: "Agriculture and Veterinary",
    highRisk: false,
  },
  {
    code: "1520",
    description: "General Contractors, Residential and Commercial",
    group: "Contractors and Trades",
    highRisk: false,
  },
  {
    code: "1711",
    description: "Heating, Plumbing, and Air Conditioning Contractors",
    group: "Contractors and Trades",
    highRisk: false,
  },
  {
    code: "1731",
    description: "Electrical Contractors",
    group: "Contractors and Trades",
    highRisk: false,
  },
  {
    code: "1740",
    description: "Masonry, Stonework, Tile Setting, Plastering and Insulation Contractors",
    group: "Contractors and Trades",
    highRisk: false,
  },
  {
    code: "1750",
    description: "Carpentry Contractors",
    group: "Contractors and Trades",
    highRisk: false,
  },
  {
    code: "1761",
    description: "Roofing, Siding, and Sheet Metal Work Contractors",
    group: "Contractors and Trades",
    highRisk: false,
  },
  {
    code: "1771",
    description: "Concrete Work Contractors",
    group: "Contractors and Trades",
    highRisk: false,
  },
  {
    code: "1799",
    description: "Special Trade Contractors (Not Elsewhere Classified)",
    group: "Contractors and Trades",
    highRisk: false,
  },
  {
    code: "2741",
    description: "Miscellaneous Publishing and Printing",
    group: "Business and Professional Services",
    highRisk: false,
  },
  {
    code: "2791",
    description: "Typesetting, Plate Making and Related Services",
    group: "Business and Professional Services",
    highRisk: false,
  },
  {
    code: "2842",
    description: "Specialty Cleaning, Polishing and Sanitation Preparations",
    group: "Business and Professional Services",
    highRisk: false,
  },
  {
    code: "4011",
    description: "Railroads",
    group: "Transportation and Freight",
    highRisk: false,
  },
  {
    code: "4111",
    description: "Local and Suburban Commuter Passenger Transportation, Including Ferries",
    group: "Transportation and Freight",
    highRisk: false,
  },
  {
    code: "4112",
    description: "Passenger Railways",
    group: "Transportation and Freight",
    highRisk: false,
  },
  {
    code: "4119",
    description: "Ambulance Services",
    group: "Transportation and Freight",
    highRisk: false,
  },
  {
    code: "4121",
    description: "Taxicabs and Limousines",
    group: "Transportation and Freight",
    highRisk: false,
  },
  {
    code: "4131",
    description: "Bus Lines",
    group: "Transportation and Freight",
    highRisk: false,
  },
  {
    code: "4214",
    description: "Motor Freight Carriers and Trucking, Local and Long Distance, Moving and Storage Companies, and Local Delivery",
    group: "Transportation and Freight",
    highRisk: false,
  },
  {
    code: "4215",
    description: "Courier Services, Air and Ground, and Freight Forwarders",
    group: "Transportation and Freight",
    highRisk: false,
  },
  {
    code: "4225",
    description: "Public Warehousing and Storage, Farm Products, Refrigerated Goods, Household Goods, and Storage",
    group: "Transportation and Freight",
    highRisk: false,
  },
  {
    code: "4411",
    description: "Steamship and Cruise Lines",
    group: "Travel and Lodging",
    highRisk: true,
  },
  {
    code: "4457",
    description: "Boat Rentals and Leasing",
    group: "Travel and Lodging",
    highRisk: false,
  },
  {
    code: "4468",
    description: "Marinas, Marine Service, and Supplies",
    group: "Transportation and Freight",
    highRisk: false,
  },
  {
    code: "4511",
    description: "Airlines and Air Carriers (Not Elsewhere Classified)",
    group: "Travel and Lodging",
    highRisk: true,
  },
  {
    code: "4582",
    description: "Airports, Flying Fields, and Airport Terminals",
    group: "Transportation and Freight",
    highRisk: false,
  },
  {
    code: "4722",
    description: "Travel Agencies and Tour Operators",
    group: "Travel and Lodging",
    highRisk: true,
  },
  {
    code: "4784",
    description: "Tolls and Bridge Fees",
    group: "Transportation and Freight",
    highRisk: false,
  },
  {
    code: "4789",
    description: "Transportation Services (Not Elsewhere Classified)",
    group: "Transportation and Freight",
    highRisk: false,
  },
  {
    code: "4812",
    description: "Telecommunication Equipment and Telephone Sales",
    group: "Utilities and Telecom",
    highRisk: false,
  },
  {
    code: "4814",
    description: "Telecommunication Services, including Local and Long-Distance Calls, Credit Card Calls, Calls Through Use of Magnetic-Stripe-Reading Telephones, and Fax Services",
    group: "Utilities and Telecom",
    highRisk: false,
  },
  {
    code: "4816",
    description: "Computer Network/Information Services",
    group: "Utilities and Telecom",
    highRisk: true,
  },
  {
    code: "4821",
    description: "Telegraph Services",
    group: "Utilities and Telecom",
    highRisk: false,
  },
  {
    code: "4829",
    description: "Money Transfer",
    group: "Financial Services",
    highRisk: true,
  },
  {
    code: "4899",
    description: "Cable, Satellite and Other Pay Television/Radio/Streaming Services",
    group: "Utilities and Telecom",
    highRisk: false,
  },
  {
    code: "4900",
    description: "Utilities, Electric, Gas, Water, and Sanitary",
    group: "Utilities and Telecom",
    highRisk: false,
  },
  {
    code: "5013",
    description: "Motor Vehicle Supplies and New Parts",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "5021",
    description: "Office and Commercial Furniture",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5039",
    description: "Construction Materials (Not Elsewhere Classified)",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5044",
    description: "Photographic, Photocopy, Microfilm Equipment and Supplies",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5045",
    description: "Computers and Computer Peripheral Equipment and Software",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5046",
    description: "Commercial Equipment (Not Elsewhere Classified)",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5047",
    description: "Medical, Dental, Ophthalmic and Hospital Equipment and Supplies",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5051",
    description: "Metal Service Centers and Offices",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5065",
    description: "Electrical Parts and Equipment",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5072",
    description: "Hardware, Equipment and Supplies",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5074",
    description: "Plumbing and Heating Equipment and Supplies",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5085",
    description: "Industrial Supplies (Not Elsewhere Classified)",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5094",
    description: "Precious Stones and Metals, Watches and Jewelry",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5099",
    description: "Durable Goods (Not Elsewhere Classified)",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5111",
    description: "Stationery, Office Supplies, Printing and Writing Paper",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5122",
    description: "Drugs, Drug Proprietaries, and Druggist Sundries",
    group: "Wholesale and Distributors",
    highRisk: true,
  },
  {
    code: "5131",
    description: "Piece Goods, Notions, and Other Dry Goods",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5137",
    description: "Men's, Women's, and Children's Uniforms and Commercial Clothing",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5139",
    description: "Commercial Footwear",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5169",
    description: "Chemicals and Allied Products (Not Elsewhere Classified)",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5172",
    description: "Petroleum and Petroleum Products",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5192",
    description: "Books, Periodicals and Newspapers",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5193",
    description: "Florists Supplies, Nursery Stock and Flowers",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5198",
    description: "Paints, Varnishes and Supplies",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5199",
    description: "Nondurable Goods (Not Elsewhere Classified)",
    group: "Wholesale and Distributors",
    highRisk: false,
  },
  {
    code: "5200",
    description: "Home Supply Warehouse Stores",
    group: "Home, Garden and Building Supply",
    highRisk: false,
  },
  {
    code: "5211",
    description: "Lumber and Building Materials Stores",
    group: "Home, Garden and Building Supply",
    highRisk: false,
  },
  {
    code: "5231",
    description: "Glass, Paint, and Wallpaper Stores",
    group: "Home, Garden and Building Supply",
    highRisk: false,
  },
  {
    code: "5251",
    description: "Hardware Stores",
    group: "Home, Garden and Building Supply",
    highRisk: false,
  },
  {
    code: "5261",
    description: "Nurseries and Lawn and Garden Supply Stores",
    group: "Home, Garden and Building Supply",
    highRisk: false,
  },
  {
    code: "5262",
    description: "Marketplaces",
    group: "General and Department Stores",
    highRisk: false,
  },
  {
    code: "5271",
    description: "Mobile Home Dealers",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "5300",
    description: "Wholesale Clubs",
    group: "General and Department Stores",
    highRisk: false,
  },
  {
    code: "5309",
    description: "Duty Free Stores",
    group: "General and Department Stores",
    highRisk: false,
  },
  {
    code: "5310",
    description: "Discount Stores",
    group: "General and Department Stores",
    highRisk: false,
  },
  {
    code: "5311",
    description: "Department Stores",
    group: "General and Department Stores",
    highRisk: false,
  },
  {
    code: "5331",
    description: "Variety Stores",
    group: "General and Department Stores",
    highRisk: false,
  },
  {
    code: "5399",
    description: "Miscellaneous General Merchandise",
    group: "General and Department Stores",
    highRisk: false,
  },
  {
    code: "5411",
    description: "Grocery Stores and Supermarkets",
    group: "Food and Grocery",
    highRisk: false,
  },
  {
    code: "5422",
    description: "Freezer and Locker Meat Provisioners",
    group: "Food and Grocery",
    highRisk: false,
  },
  {
    code: "5441",
    description: "Candy, Nut, and Confectionery Stores",
    group: "Food and Grocery",
    highRisk: false,
  },
  {
    code: "5451",
    description: "Dairy Products Stores",
    group: "Food and Grocery",
    highRisk: false,
  },
  {
    code: "5462",
    description: "Bakeries",
    group: "Food and Grocery",
    highRisk: false,
  },
  {
    code: "5499",
    description: "Miscellaneous Food Stores, Convenience Stores and Specialty Markets",
    group: "Food and Grocery",
    highRisk: false,
  },
  {
    code: "5511",
    description: "Car and Truck Dealers (New and Used) Sales, Service, Repairs, Parts, and Leasing",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "5521",
    description: "Car and Truck Dealers (Used Only) Sales, Service, Repairs, Parts, and Leasing",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "5532",
    description: "Automotive Tire Stores",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "5533",
    description: "Automotive Parts and Accessories Stores",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "5541",
    description: "Service Stations (With or without Ancillary Services)",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "5542",
    description: "Automated Fuel Dispensers",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "5551",
    description: "Boat Dealers",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "5552",
    description: "Electric Vehicle Charging",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "5561",
    description: "Camper, Recreational and Utility Trailer Dealers",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "5571",
    description: "Motorcycle Shops and Dealers",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "5592",
    description: "Motor Homes Dealers",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "5598",
    description: "Snowmobile Dealers",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "5599",
    description: "Miscellaneous Automotive, Aircraft, and Farm Equipment Dealers (Not Elsewhere Classified)",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "5611",
    description: "Men's and Boys' Clothing and Accessories Stores",
    group: "Clothing and Accessories",
    highRisk: false,
  },
  {
    code: "5621",
    description: "Women's Ready-To-Wear Stores",
    group: "Clothing and Accessories",
    highRisk: false,
  },
  {
    code: "5631",
    description: "Women's Accessory and Specialty Shops",
    group: "Clothing and Accessories",
    highRisk: false,
  },
  {
    code: "5641",
    description: "Children's and Infants' Wear Stores",
    group: "Clothing and Accessories",
    highRisk: false,
  },
  {
    code: "5651",
    description: "Family Clothing Stores",
    group: "Clothing and Accessories",
    highRisk: false,
  },
  {
    code: "5655",
    description: "Sports and Riding Apparel Stores",
    group: "Clothing and Accessories",
    highRisk: false,
  },
  {
    code: "5661",
    description: "Shoe Stores",
    group: "Clothing and Accessories",
    highRisk: false,
  },
  {
    code: "5681",
    description: "Furriers and Fur Shops",
    group: "Clothing and Accessories",
    highRisk: false,
  },
  {
    code: "5691",
    description: "Men's and Women's Clothing Stores",
    group: "Clothing and Accessories",
    highRisk: false,
  },
  {
    code: "5697",
    description: "Tailors, Seamstresses, Mending, and Alterations",
    group: "Clothing and Accessories",
    highRisk: false,
  },
  {
    code: "5698",
    description: "Wig and Toupee Stores",
    group: "Clothing and Accessories",
    highRisk: false,
  },
  {
    code: "5699",
    description: "Miscellaneous Apparel and Accessory Shops",
    group: "Clothing and Accessories",
    highRisk: false,
  },
  {
    code: "5712",
    description: "Furniture, Home Furnishings, and Equipment Stores, Except Appliances",
    group: "Home, Garden and Building Supply",
    highRisk: false,
  },
  {
    code: "5713",
    description: "Floor Covering Stores",
    group: "Home, Garden and Building Supply",
    highRisk: false,
  },
  {
    code: "5714",
    description: "Drapery, Window Covering, and Upholstery Stores",
    group: "Home, Garden and Building Supply",
    highRisk: false,
  },
  {
    code: "5718",
    description: "Fireplace, Fireplace Screens and Accessories Stores",
    group: "Home, Garden and Building Supply",
    highRisk: false,
  },
  {
    code: "5719",
    description: "Miscellaneous Home Furnishing Specialty Stores",
    group: "Home, Garden and Building Supply",
    highRisk: false,
  },
  {
    code: "5722",
    description: "Household Appliance Stores",
    group: "Home, Garden and Building Supply",
    highRisk: false,
  },
  {
    code: "5723",
    description: "Guns and Ammunition Shops",
    group: "Specialty and Hobby Retail",
    highRisk: true,
  },
  {
    code: "5732",
    description: "Electronics Stores",
    group: "Electronics and Computers",
    highRisk: false,
  },
  {
    code: "5733",
    description: "Music Stores, Musical Instruments, Pianos, and Sheet Music",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5734",
    description: "Computer Software Stores",
    group: "Electronics and Computers",
    highRisk: false,
  },
  {
    code: "5735",
    description: "Record Stores",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5811",
    description: "Caterers",
    group: "Restaurants and Bars",
    highRisk: false,
  },
  {
    code: "5812",
    description: "Eating Places and Restaurants",
    group: "Restaurants and Bars",
    highRisk: false,
  },
  {
    code: "5813",
    description: "Drinking Places (Alcoholic Beverages), Bars, Taverns, Nightclubs, Cocktail Lounges, and Discotheques",
    group: "Restaurants and Bars",
    highRisk: false,
  },
  {
    code: "5814",
    description: "Fast Food Restaurants",
    group: "Restaurants and Bars",
    highRisk: false,
  },
  {
    code: "5815",
    description: "Digital Goods Media, Books, Movies, Digital artwork/images, Music",
    group: "Digital Goods and Direct Marketing",
    highRisk: false,
  },
  {
    code: "5816",
    description: "Digital Goods, Games",
    group: "Digital Goods and Direct Marketing",
    highRisk: true,
  },
  {
    code: "5817",
    description: "Digital Goods, Applications (Excludes Games)",
    group: "Digital Goods and Direct Marketing",
    highRisk: false,
  },
  {
    code: "5818",
    description: "Digital Goods, Large Digital Goods Merchant",
    group: "Digital Goods and Direct Marketing",
    highRisk: false,
  },
  {
    code: "5912",
    description: "Drug Stores and Pharmacies",
    group: "Health and Medical",
    highRisk: true,
  },
  {
    code: "5921",
    description: "Package Stores, Beer, Wine, and Liquor",
    group: "Food and Grocery",
    highRisk: false,
  },
  {
    code: "5931",
    description: "Used Merchandise and Secondhand Stores",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5932",
    description: "Antique Shops, Sales, Repairs, and Restoration Services",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5933",
    description: "Pawn Shops",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5935",
    description: "Wrecking and Salvage Yards",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5937",
    description: "Antique Reproductions",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5940",
    description: "Bicycle Shops, Sales and Service",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5941",
    description: "Sporting Goods Stores",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5942",
    description: "Book Stores",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5943",
    description: "Stationery Stores, Office and School Supply Stores",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5944",
    description: "Jewelry Stores, Watches, Clocks, and Silverware Stores",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5945",
    description: "Hobby, Toy, and Game Shops",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5946",
    description: "Camera and Photographic Supply Stores",
    group: "Electronics and Computers",
    highRisk: false,
  },
  {
    code: "5947",
    description: "Gift, Card, Novelty and Souvenir Shops",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5948",
    description: "Luggage and Leather Goods Stores",
    group: "Clothing and Accessories",
    highRisk: false,
  },
  {
    code: "5949",
    description: "Sewing, Needlework, Fabric and Piece Goods Stores",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5950",
    description: "Glassware/Crystal Stores",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5960",
    description: "Direct Marketing, Insurance Services",
    group: "Digital Goods and Direct Marketing",
    highRisk: false,
  },
  {
    code: "5962",
    description: "Direct Marketing, Travel-Related Arrangement Services",
    group: "Digital Goods and Direct Marketing",
    highRisk: true,
  },
  {
    code: "5963",
    description: "Door-To-Door Sales",
    group: "Digital Goods and Direct Marketing",
    highRisk: true,
  },
  {
    code: "5964",
    description: "Direct Marketing, Catalog Merchant",
    group: "Digital Goods and Direct Marketing",
    highRisk: false,
  },
  {
    code: "5965",
    description: "Direct Marketing, Combination Catalog and Retail Merchant",
    group: "Digital Goods and Direct Marketing",
    highRisk: false,
  },
  {
    code: "5966",
    description: "Direct Marketing, Outbound Telemarketing Merchant",
    group: "Digital Goods and Direct Marketing",
    highRisk: true,
  },
  {
    code: "5967",
    description: "Adult Content and Services",
    group: "Digital Goods and Direct Marketing",
    highRisk: true,
  },
  {
    code: "5968",
    description: "Direct Marketing, Continuity/Subscription Merchant",
    group: "Digital Goods and Direct Marketing",
    highRisk: true,
  },
  {
    code: "5969",
    description: "Direct Marketing, Other Direct Marketers (Not Elsewhere Classified)",
    group: "Digital Goods and Direct Marketing",
    highRisk: false,
  },
  {
    code: "5970",
    description: "Artists' Supply and Craft Shops",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5971",
    description: "Art Dealers and Galleries",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5972",
    description: "Stamp and Coin Stores",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5973",
    description: "Religious Goods Stores",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5975",
    description: "Hearing Aids, Sales, Service, and Supply",
    group: "Health and Medical",
    highRisk: false,
  },
  {
    code: "5976",
    description: "Orthopedic Goods, Prosthetic Devices",
    group: "Health and Medical",
    highRisk: false,
  },
  {
    code: "5977",
    description: "Cosmetic Stores",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5978",
    description: "Typewriter Stores, Sales, Rentals, and Service",
    group: "Electronics and Computers",
    highRisk: false,
  },
  {
    code: "5983",
    description: "Fuel Dealers, Fuel Oil, Wood, Coal, and Liquefied Petroleum",
    group: "Utilities and Telecom",
    highRisk: false,
  },
  {
    code: "5992",
    description: "Florists",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5993",
    description: "Cigar Stores and Stands",
    group: "Specialty and Hobby Retail",
    highRisk: true,
  },
  {
    code: "5994",
    description: "News Dealers and Newsstands",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5995",
    description: "Pet Shops, Pet Foods and Supplies Stores",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "5996",
    description: "Swimming Pools, Sales and Service",
    group: "Home, Garden and Building Supply",
    highRisk: false,
  },
  {
    code: "5997",
    description: "Electric Razor Stores, Sales and Service",
    group: "Electronics and Computers",
    highRisk: false,
  },
  {
    code: "5998",
    description: "Tent and Awning Shops",
    group: "Home, Garden and Building Supply",
    highRisk: false,
  },
  {
    code: "5999",
    description: "Miscellaneous and Specialty Retail Shops",
    group: "Specialty and Hobby Retail",
    highRisk: false,
  },
  {
    code: "6010",
    description: "Financial Institutions, Manual Cash Disbursements",
    group: "Financial Services",
    highRisk: true,
  },
  {
    code: "6011",
    description: "Financial Institutions, Automated Cash Disbursements",
    group: "Financial Services",
    highRisk: true,
  },
  {
    code: "6012",
    description: "Financial Institutions, Merchandise, Services, and Debt Repayment",
    group: "Financial Services",
    highRisk: true,
  },
  {
    code: "6051",
    description: "Non-Financial Institutions, Foreign Currency, Liquid and Cryptocurrency Assets (for example: Cryptocurrency), Money Orders (Not Money Transfer), Account Funding (not Stored Value Load), Travelers Cheques, and Debt Repayment",
    group: "Financial Services",
    highRisk: true,
  },
  {
    code: "6211",
    description: "Security Brokers/Dealers",
    group: "Financial Services",
    highRisk: true,
  },
  {
    code: "6300",
    description: "Insurance Sales, Underwriting, and Premiums",
    group: "Financial Services",
    highRisk: false,
  },
  {
    code: "6513",
    description: "Real Estate Agents and Managers",
    group: "Financial Services",
    highRisk: false,
  },
  {
    code: "6540",
    description: "Non-Financial Institutions, Stored Value Card Purchase/Load",
    group: "Financial Services",
    highRisk: true,
  },
  {
    code: "7011",
    description: "Lodging, Hotels, Motels, Resorts, Central Reservation Services (Not Elsewhere Classified)",
    group: "Travel and Lodging",
    highRisk: false,
  },
  {
    code: "7012",
    description: "Timeshares",
    group: "Travel and Lodging",
    highRisk: true,
  },
  {
    code: "7032",
    description: "Sporting and Recreational Camps",
    group: "Travel and Lodging",
    highRisk: false,
  },
  {
    code: "7033",
    description: "Trailer Parks and Campgrounds",
    group: "Travel and Lodging",
    highRisk: false,
  },
  {
    code: "7210",
    description: "Laundry, Cleaning, and Garment Services",
    group: "Personal Services",
    highRisk: false,
  },
  {
    code: "7211",
    description: "Laundries, Family and Commercial",
    group: "Personal Services",
    highRisk: false,
  },
  {
    code: "7216",
    description: "Dry Cleaners",
    group: "Personal Services",
    highRisk: false,
  },
  {
    code: "7217",
    description: "Carpet and Upholstery Cleaning",
    group: "Home, Garden and Building Supply",
    highRisk: false,
  },
  {
    code: "7221",
    description: "Photographic Studios",
    group: "Personal Services",
    highRisk: false,
  },
  {
    code: "7230",
    description: "Beauty and Barber Shops",
    group: "Personal Services",
    highRisk: false,
  },
  {
    code: "7251",
    description: "Shoe Repair Shops, Shoeshine Parlors, and Hat Cleaning Shops",
    group: "Personal Services",
    highRisk: false,
  },
  {
    code: "7261",
    description: "Funeral Services and Crematories",
    group: "Personal Services",
    highRisk: false,
  },
  {
    code: "7273",
    description: "Dating Services",
    group: "Personal Services",
    highRisk: true,
  },
  {
    code: "7276",
    description: "Tax Preparation Services",
    group: "Personal Services",
    highRisk: false,
  },
  {
    code: "7277",
    description: "Counseling Services, Debt, Marriage, and Personal",
    group: "Personal Services",
    highRisk: true,
  },
  {
    code: "7278",
    description: "Buying and Shopping Services and Clubs",
    group: "Personal Services",
    highRisk: false,
  },
  {
    code: "7296",
    description: "Clothing Rental, Costumes, Uniforms, Formal Wear",
    group: "Clothing and Accessories",
    highRisk: false,
  },
  {
    code: "7297",
    description: "Massage Parlors",
    group: "Personal Services",
    highRisk: true,
  },
  {
    code: "7298",
    description: "Health and Beauty Spas",
    group: "Personal Services",
    highRisk: false,
  },
  {
    code: "7299",
    description: "Miscellaneous Personal Services (Not Elsewhere Classified)",
    group: "Personal Services",
    highRisk: false,
  },
  {
    code: "7311",
    description: "Advertising Services",
    group: "Business and Professional Services",
    highRisk: false,
  },
  {
    code: "7321",
    description: "Consumer Credit Reporting Agencies",
    group: "Business and Professional Services",
    highRisk: true,
  },
  {
    code: "7322",
    description: "Collection Agencies",
    group: "Business and Professional Services",
    highRisk: true,
  },
  {
    code: "7333",
    description: "Commercial Photography, Art, and Graphics",
    group: "Business and Professional Services",
    highRisk: false,
  },
  {
    code: "7338",
    description: "Quick Copy, Reproduction, and Blueprinting Services",
    group: "Business and Professional Services",
    highRisk: false,
  },
  {
    code: "7339",
    description: "Stenographic and Secretarial Support",
    group: "Business and Professional Services",
    highRisk: false,
  },
  {
    code: "7342",
    description: "Exterminating and Disinfecting Services",
    group: "Contractors and Trades",
    highRisk: false,
  },
  {
    code: "7349",
    description: "Cleaning, Maintenance, and Janitorial Services",
    group: "Contractors and Trades",
    highRisk: false,
  },
  {
    code: "7361",
    description: "Employment Agencies and Temporary Help Services",
    group: "Business and Professional Services",
    highRisk: false,
  },
  {
    code: "7372",
    description: "Computer Programming, Data Processing, and Integrated Systems Design Services",
    group: "Electronics and Computers",
    highRisk: false,
  },
  {
    code: "7375",
    description: "Information Retrieval Services",
    group: "Electronics and Computers",
    highRisk: false,
  },
  {
    code: "7379",
    description: "Computer Maintenance, Repair and Services (Not Elsewhere Classified)",
    group: "Electronics and Computers",
    highRisk: false,
  },
  {
    code: "7392",
    description: "Management, Consulting, and Public Relations Services",
    group: "Business and Professional Services",
    highRisk: false,
  },
  {
    code: "7393",
    description: "Detective Agencies, Protective Services, and Security Services, including Armored Cars, and Guard Dogs",
    group: "Business and Professional Services",
    highRisk: false,
  },
  {
    code: "7394",
    description: "Equipment, Tool, Furniture, and Appliance Rental and Leasing",
    group: "Personal Services",
    highRisk: false,
  },
  {
    code: "7395",
    description: "Photofinishing Laboratories and Photo Developing",
    group: "Personal Services",
    highRisk: false,
  },
  {
    code: "7399",
    description: "Business Services (Not Elsewhere Classified)",
    group: "Business and Professional Services",
    highRisk: false,
  },
  {
    code: "7512",
    description: "Automobile Rental Agency",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "7513",
    description: "Truck and Utility Trailer Rentals",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "7519",
    description: "Motor Home and Recreational Vehicle Rentals",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "7523",
    description: "Parking Lots, Parking Meters and Garages",
    group: "Transportation and Freight",
    highRisk: false,
  },
  {
    code: "7531",
    description: "Automotive Body Repair Shops",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "7534",
    description: "Tire Retreading and Repair Shops",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "7535",
    description: "Automotive Paint Shops",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "7538",
    description: "Automotive Service Shops (Non-Dealer)",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "7542",
    description: "Car Washes",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "7549",
    description: "Towing Services",
    group: "Automotive",
    highRisk: false,
  },
  {
    code: "7622",
    description: "Electronics Repair Shops",
    group: "Electronics and Computers",
    highRisk: false,
  },
  {
    code: "7623",
    description: "Air Conditioning and Refrigeration Repair Shops",
    group: "Contractors and Trades",
    highRisk: false,
  },
  {
    code: "7629",
    description: "Electrical and Small Appliance Repair Shops",
    group: "Electronics and Computers",
    highRisk: false,
  },
  {
    code: "7631",
    description: "Watch, Clock and Jewelry Repair",
    group: "Personal Services",
    highRisk: false,
  },
  {
    code: "7641",
    description: "Furniture, Reupholstery, Repair, and Refinishing",
    group: "Home, Garden and Building Supply",
    highRisk: false,
  },
  {
    code: "7692",
    description: "Welding Services",
    group: "Contractors and Trades",
    highRisk: false,
  },
  {
    code: "7699",
    description: "Miscellaneous Repair Shops and Related Services",
    group: "Business and Professional Services",
    highRisk: false,
  },
  {
    code: "7800",
    description: "Government-Owned Lotteries (US Region only)",
    group: "Entertainment and Recreation",
    highRisk: true,
  },
  {
    code: "7801",
    description: "Government Licensed On-Line Casinos (On-Line Gambling) (US Region only)",
    group: "Entertainment and Recreation",
    highRisk: true,
  },
  {
    code: "7802",
    description: "Government-Licensed Horse/Dog Racing (US Region only)",
    group: "Entertainment and Recreation",
    highRisk: true,
  },
  {
    code: "7829",
    description: "Motion Picture and Video Tape Production and Distribution",
    group: "Entertainment and Recreation",
    highRisk: false,
  },
  {
    code: "7832",
    description: "Motion Picture Theaters",
    group: "Entertainment and Recreation",
    highRisk: false,
  },
  {
    code: "7841",
    description: "DVD/Video Tape Rental Stores",
    group: "Entertainment and Recreation",
    highRisk: false,
  },
  {
    code: "7911",
    description: "Dance Halls, Studios and Schools",
    group: "Entertainment and Recreation",
    highRisk: false,
  },
  {
    code: "7922",
    description: "Ticket Agencies and Theatrical Producers (Except Motion Pictures)",
    group: "Entertainment and Recreation",
    highRisk: false,
  },
  {
    code: "7929",
    description: "Bands, Orchestras, and Miscellaneous Entertainers (Not Elsewhere Classified)",
    group: "Entertainment and Recreation",
    highRisk: false,
  },
  {
    code: "7932",
    description: "Billiard and Pool Establishments",
    group: "Entertainment and Recreation",
    highRisk: false,
  },
  {
    code: "7933",
    description: "Bowling Alleys",
    group: "Entertainment and Recreation",
    highRisk: false,
  },
  {
    code: "7941",
    description: "Commercial Sports, Professional Sports Clubs, Athletic Fields, and Sports Promoters",
    group: "Entertainment and Recreation",
    highRisk: false,
  },
  {
    code: "7991",
    description: "Tourist Attractions and Exhibits",
    group: "Entertainment and Recreation",
    highRisk: false,
  },
  {
    code: "7992",
    description: "Public Golf Courses",
    group: "Entertainment and Recreation",
    highRisk: false,
  },
  {
    code: "7993",
    description: "Video Amusement Game Supplies",
    group: "Entertainment and Recreation",
    highRisk: false,
  },
  {
    code: "7994",
    description: "Video Game Arcades/Establishments",
    group: "Entertainment and Recreation",
    highRisk: false,
  },
  {
    code: "7995",
    description: "Betting, including Lottery Tickets, Casino Gaming Chips, Off-Track Betting, Wagers at Race Tracks and games of chance to win prizes of monetary value",
    group: "Entertainment and Recreation",
    highRisk: true,
  },
  {
    code: "7996",
    description: "Amusement Parks, Circuses, Carnivals, and Fortune Tellers",
    group: "Entertainment and Recreation",
    highRisk: false,
  },
  {
    code: "7997",
    description: "Membership Clubs (Sports, Recreation, Athletic), Country Clubs, and Private Golf Courses",
    group: "Entertainment and Recreation",
    highRisk: false,
  },
  {
    code: "7998",
    description: "Aquariums, Seaquariums, Dolphinariums, and Zoos",
    group: "Entertainment and Recreation",
    highRisk: false,
  },
  {
    code: "7999",
    description: "Recreation Services (Not Elsewhere Classified)",
    group: "Entertainment and Recreation",
    highRisk: false,
  },
  {
    code: "8011",
    description: "Doctors and Physicians (Not Elsewhere Classified)",
    group: "Health and Medical",
    highRisk: false,
  },
  {
    code: "8021",
    description: "Dentists and Orthodontists",
    group: "Health and Medical",
    highRisk: false,
  },
  {
    code: "8031",
    description: "Osteopaths",
    group: "Health and Medical",
    highRisk: false,
  },
  {
    code: "8041",
    description: "Chiropractors",
    group: "Health and Medical",
    highRisk: false,
  },
  {
    code: "8042",
    description: "Optometrists and Ophthalmologists",
    group: "Health and Medical",
    highRisk: false,
  },
  {
    code: "8043",
    description: "Opticians, Optical Goods, and Eyeglasses",
    group: "Health and Medical",
    highRisk: false,
  },
  {
    code: "8049",
    description: "Podiatrists and Chiropodists",
    group: "Health and Medical",
    highRisk: false,
  },
  {
    code: "8050",
    description: "Nursing, Home Healthcare and Personal Care Facilities",
    group: "Health and Medical",
    highRisk: false,
  },
  {
    code: "8062",
    description: "Hospitals",
    group: "Health and Medical",
    highRisk: false,
  },
  {
    code: "8071",
    description: "Medical and Dental Laboratories",
    group: "Health and Medical",
    highRisk: false,
  },
  {
    code: "8099",
    description: "Medical Services and Health Practitioners (Not Elsewhere Classified)",
    group: "Health and Medical",
    highRisk: false,
  },
  {
    code: "8111",
    description: "Legal Services and Attorneys",
    group: "Business and Professional Services",
    highRisk: false,
  },
  {
    code: "8211",
    description: "Elementary and Secondary Schools",
    group: "Education",
    highRisk: false,
  },
  {
    code: "8220",
    description: "Colleges, Universities, Professional Schools, and Junior Colleges",
    group: "Education",
    highRisk: false,
  },
  {
    code: "8241",
    description: "Correspondence Schools",
    group: "Education",
    highRisk: false,
  },
  {
    code: "8244",
    description: "Business and Secretarial Schools",
    group: "Education",
    highRisk: false,
  },
  {
    code: "8249",
    description: "Vocational and Trade Schools",
    group: "Education",
    highRisk: false,
  },
  {
    code: "8299",
    description: "Schools and Educational Services (Not Elsewhere Classified)",
    group: "Education",
    highRisk: false,
  },
  {
    code: "8351",
    description: "Child Care Services",
    group: "Education",
    highRisk: false,
  },
  {
    code: "8398",
    description: "Charitable Social Service Organizations",
    group: "Membership and Nonprofit",
    highRisk: false,
  },
  {
    code: "8641",
    description: "Civic, Social, and Fraternal Associations",
    group: "Membership and Nonprofit",
    highRisk: false,
  },
  {
    code: "8651",
    description: "Political Organizations",
    group: "Membership and Nonprofit",
    highRisk: false,
  },
  {
    code: "8661",
    description: "Religious Organizations",
    group: "Membership and Nonprofit",
    highRisk: false,
  },
  {
    code: "8675",
    description: "Automobile Associations",
    group: "Membership and Nonprofit",
    highRisk: false,
  },
  {
    code: "8699",
    description: "Membership Organizations (Not Elsewhere Classified)",
    group: "Membership and Nonprofit",
    highRisk: false,
  },
  {
    code: "8734",
    description: "Testing Laboratories (Non-Medical Testing)",
    group: "Business and Professional Services",
    highRisk: false,
  },
  {
    code: "8911",
    description: "Architectural, Engineering, and Surveying Services",
    group: "Business and Professional Services",
    highRisk: false,
  },
  {
    code: "8931",
    description: "Accounting, Auditing, and Bookkeeping Services",
    group: "Business and Professional Services",
    highRisk: false,
  },
  {
    code: "8999",
    description: "Professional Services (Not Elsewhere Classified)",
    group: "Business and Professional Services",
    highRisk: false,
  },
  {
    code: "9211",
    description: "Court Costs, Including Alimony and Child Support",
    group: "Government and Public Sector",
    highRisk: false,
  },
  {
    code: "9222",
    description: "Fines",
    group: "Government and Public Sector",
    highRisk: false,
  },
  {
    code: "9223",
    description: "Bail and Bond Payments",
    group: "Government and Public Sector",
    highRisk: true,
  },
  {
    code: "9311",
    description: "Tax Payments",
    group: "Government and Public Sector",
    highRisk: false,
  },
  {
    code: "9399",
    description: "Government Services (Not Elsewhere Classified)",
    group: "Government and Public Sector",
    highRisk: false,
  },
  {
    code: "9402",
    description: "Postal Services, Government Only",
    group: "Government and Public Sector",
    highRisk: false,
  },
  {
    code: "9405",
    description: "U.S. Federal Government Agencies or Departments",
    group: "Government and Public Sector",
    highRisk: false,
  },
  {
    code: "9950",
    description: "Intra-Company Purchases",
    group: "Government and Public Sector",
    highRisk: false,
  },
];
